# Generated by Django 4.1.4 on 2023-01-05 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_cart_delivdeliry_charge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='delivdeliry_charge',
            new_name='deliveliry_charge',
        ),
    ]
