# Generated by Django 4.1.4 on 2023-01-05 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_delivdeliry_charge_cart_deliveliry_charge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='deliveliry_charge',
            new_name='delivery_charge',
        ),
    ]
